name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set STAGE to production (we assume staging if not set)
        if: startsWith(github.event.deployment.environment, 'production')
        run: |
          echo "::set-env name=STAGE::production"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test --if-present
        env:
          CI: true
      - run: npm run deploy:assets --if-present # deploy just this branch
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Failure output
      - name: 'Deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'failure'
          token: '${{ github.token }}'

      # Success outputs
      - name: 'Deployment success review'
        if: success() && startsWith(github.event.deployment.environment, 'pr')
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'
          environment-url: https://helloworld.staging.hbkapps.com/deploys/${{ github.sha }}/index.html
      - name: 'Deployment success staging'
        if: success() && startsWith(github.event.deployment.environment, 'staging')
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'
          environment-url: https://helloworld.staging.hbkapps.com/index.html
      - name: 'Deployment success production'
        if: success() && startsWith(github.event.deployment.environment, 'production')
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'
          environment-url: https://helloworld.production.hbkapps.com/
        