name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha
        id: short-sha
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build --if-present
        env:
          STAGE: staging
      # - run: npm test --if-present
      #   env:
      #     CI: true
      - run: npm run deploy:assets --if-present # deploy just this branch
        env:
          STAGE: staging # this will eventually based on deploybot
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Deploy ${{ github.event.deployment.environment }}'
        run: |
          echo "task - ${{ github.event.deployment.task }}"
          echo "environment - ${{ github.event.deployment.task }}"
          echo "payload - ${{ github.event.deployment.payload }}"

      - name: 'Deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'
          environment-url: https://helloworld.hbkapps.com/${{ steps.short-sha.outputs.sha }}/index.html

      - name: 'Deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'failure'
          token: '${{ github.token }}'

        